import { useState, useEffect } from 'react';
import VideoPlayer from './components/VideoPlayer';
import './App.css';

// ─── Movie Configuration ──────────────────────────────────────────────────────
// Original MKV (EAC3 audio — no browser sound)
const MOVIE_ORIGINAL = '/95-satluj.mkv';
// AAC-converted version (being generated by FFmpeg — has sound ✓)
const MOVIE_AAC      = '/95-satluj-aac.mkv';
const MOVIE_TITLE    = '95-Satluj';

/**
 * Checks if the AAC-converted file exists on the server.
 * Returns true if the file is ready (HTTP 200/206), false otherwise.
 */
async function checkAacReady() {
  try {
    const res = await fetch(MOVIE_AAC, { method: 'HEAD' });
    return res.ok;
  } catch {
    return false;
  }
}

function App() {
  // Start with the original file; switch to AAC version once it's ready
  const [movieSrc, setMovieSrc] = useState(MOVIE_ORIGINAL);
  const [aacReady, setAacReady] = useState(false);
  const [checking, setChecking] = useState(true);

  // Poll every 10s until the AAC file appears (FFmpeg conversion running)
  useEffect(() => {
    let timer;

    const poll = async () => {
      const ready = await checkAacReady();
      if (ready) {
        setAacReady(true);
        setMovieSrc(MOVIE_AAC);
        setChecking(false);
      } else {
        setChecking(false);
        // Re-check every 15 seconds
        timer = setTimeout(poll, 15000);
      }
    };

    poll();
    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="app" id="app">
      {/* Header */}
      <header className="app-header" id="app-header">
        <div className="app-header__logo">
          <svg viewBox="0 0 24 24" fill="currentColor" width="28" height="28">
            <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 14.5v-9l6 4.5-6 4.5z" />
          </svg>
          <span>CinePlay</span>
        </div>
        <div className="app-header__badge">
          {aacReady ? '🔊 AAC Audio' : 'MKV Ready'}
        </div>
      </header>

      {/* Audio conversion status banner */}
      {!aacReady && (
        <div className={`conversion-banner ${checking ? 'conversion-banner--checking' : 'conversion-banner--converting'}`} id="conversion-banner">
          <div className="cb-icon">{checking ? '🔍' : '⚙️'}</div>
          <div className="cb-text">
            {checking
              ? 'Checking for AAC audio file…'
              : <>
                  <strong>Converting audio: EAC3 → AAC</strong>
                  <span> — FFmpeg is running in background. Sound will work once done (~20 min). Video plays without sound now.</span>
                </>
            }
          </div>
          <div className="cb-spinner" />
        </div>
      )}

      {/* AAC ready banner */}
      {aacReady && (
        <div className="conversion-banner conversion-banner--done" id="aac-ready-banner">
          <div className="cb-icon">✅</div>
          <div className="cb-text">
            <strong>Audio Fixed!</strong>
            <span> Playing AAC version — full 5.1 surround sound works.</span>
          </div>
        </div>
      )}

      {/* Main: Player */}
      <main className="app-main app-main--player" id="app-main">
        <div className="player-wrapper" id="player-wrapper">
          {/* Keyboard hints */}
          <div className="shortcut-bar">
            <span className="kb-hint"><kbd>Space</kbd> Play/Pause</span>
            <span className="kb-hint"><kbd>←</kbd> <kbd>→</kbd> Skip 10s</span>
            <span className="kb-hint"><kbd>↑</kbd> <kbd>↓</kbd> Volume</span>
            <span className="kb-hint"><kbd>M</kbd> Mute</span>
            <span className="kb-hint"><kbd>F</kbd> Fullscreen</span>
          </div>

          {/* Video player */}
          <VideoPlayer src={movieSrc} title={MOVIE_TITLE} />

          {/* File info */}
          <div className="file-path-hint">
            <svg viewBox="0 0 24 24" fill="currentColor" width="14" height="14">
              <path d="M10 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2h-8l-2-2z" />
            </svg>
            <span>
              Playing: <code>{movieSrc}</code>
              {aacReady && <span className="hint-green"> · AAC audio ✓</span>}
            </span>
          </div>
        </div>
      </main>
    </div>
  );
}

export default App;
